Access tests through lui_menu.  Cleaned up test and removed obsolete tests.

diff --git a/list_ui_test b/list_ui_test
--- a/list_ui_test
+++ b/list_ui_test
@@ -36,6 +36,8 @@ declare -a LONGLIST=(
 )
 lui_list_init "LONGLIST"
 
+# This is not a test, but rather a function that displays the contents
+# of a lui_list.
 test_dump_list()
 {
     local -n tdl_list="$1"
@@ -62,6 +64,7 @@ test_dump_list()
 
 test_padding()
 {
+    reset_screen
     local -i padding=$( lui_list_max_len_by_column "MYLIST" 0 )
     local -a lrow
     local -i rows
@@ -72,17 +75,8 @@ test_padding()
         hilite_pad "${lrow[0]}" "$padding"
         echo $'\e[m'
     done
-}
 
-test_simple_menu()
-{
-    local -i selected_index
-
-    if lui_list_menu "selected_index" "LONGLIST"; then
-        echo "You selected index $selected_index"
-    else
-        echo "You cancelled the selection."
-    fi
+    read -n1 -p "Press any key to return to the main menu."
 }
 
 # Creates a proper lui_list array with the contents of the LS_COLORS
@@ -151,7 +145,7 @@ test_ls_colors()
     create_ls_colors_array "list_colors" 3
 
     local -i selection=0
-    if lui_list_task "selection" "list_colors" "ls_colors_displayer" 20; then
+    if lui_list_generic "selection" "list_colors" "ls_colors_displayer" 20; then
         local -a row
         if ! lui_list_copy_row "row" "list_colors" "$selection"; then
             echo "The attempt to access line number $selection caused a failure."
@@ -160,19 +154,8 @@ test_ls_colors()
 
         echo "You selected index $selection, which looks "$'\e['"${row[1]}mlike this"$'\e[m'
     fi
-}
 
-test_generic_edit_color()
-{
-    local keyp="$1"
-    local list_name="$2"
-    local -i row_number="$3"
-
-    local -a row
-    if lui_list_copy_row "row" "$list_name" "$row_number"; then
-        edit_color "${row[1]}"
-    fi
-    return 0
+    read -n1 -p "Press any key to continue."
 }
 
 test_generic_menu()
@@ -189,87 +172,120 @@ test_generic_menu()
     fi
 }
 
-test_radio_toggler()
+test_simple_menu()
 {
-    # prevent space from being disacarded
-    local OIFS="$IFS"
-    IFS=''
+    local -i selected_index
 
-    local keyp="$1"
-    local list_name="$2"
-    local -i row_target="$3"
+    if lui_list_menu "selected_index" "MYLIST"; then
+        echo "You selected index $selected_index"
+    else
+        echo "You cancelled the selection."
+    fi
+}
 
-    IFS="$OIFS"
+test_custom_menu()
+{
+    local -i tcm_selected=0
 
-    local -n trt_list="$list_name"
-    local -i col_count="${trt_list[0]}"
-    local -i flag_column=$(( col_count - 1 ))
-    local -i row_count="${trt_list[1]}"
-    local -i cur_row=0
-    local -i val
+    tcm_display_line()
+    {
+        local -i hilite="$1"
+        local -i padding="$2"
+        local -a row=( "${@:3}" )
 
-    local -a row=()
-    local el
-    for el in "${trt_list[@]:2}"; do
-        row+=( "$el" )
-        if [ "${#row[@]}" -eq "$col_count" ]; then
-            val="${row[$flag_column]}"
-            if [ "$cur_row" -eq "$row_target" ]; then
-                (( row[$flag_column] = (val+1) % 2 ))
-                lui_list_replace_row "$list_name" "row" "$cur_row"
-            elif [ "$val" -ne 0 ]; then
-                (( row[$flag_column] = 0 ))
-                lui_list_replace_row "$list_name" "row" "$cur_row"
+        if [ "$hilite" -ne 0 ]; then echo -n $'\e[43m'; fi
+        hilite_pad "${row[0]}" "$padding"
+        echo $'\e[m'
+    }
+
+    lui_list_generic "tcm_selected" "MYLIST" "tcm_display_line" 10
+
+    echo "You selected item index $tcm_selected."
+    read -n1 -p "Press any key to continue."
+}
+
+report_selection()
+{
+    local -n sel_list="$1"
+    local -i rows
+    lui_list_row_count "rows" "$1"
+    local -a selections=()
+    local -a row
+    for (( ndx=0; ndx < rows; ++ndx )); do
+        if lui_list_copy_row "row" "$1" "$ndx"; then
+            if [ "${row[1]}" -ne 0 ]; then
+                selections+=( "${row[0]}" )
             fi
-            (( ++cur_row ))
-            row=()
         fi
     done
 
-    return 0
-}
-
-test_radio_displayer()
-{
-    local -i hilite="$1"
-    local -i padding="$2"
-    local -a els=( "${@:3}" )
-    local -i selected="${els[@]: -1}"
-    if [ "$hilite" -eq 1 ]; then
-        echo -n ">>> "
+    if [ "${#selections[@]}" -eq 0 ]; then
+        echo "You made no selections."
     else
-        echo -n "    "
+        local sel
+        echo -n "You made ${#selections[@]} selections: ${selections[0]}"
+        for sel in "${selections[@]:1}"; do
+            echo -n ", $sel"
+        done
+        echo "."
     fi
-    if [ "$selected" -eq 0 ]; then
-        echo -n "[ ] "
-    else
-        echo -n "[x] "
-    fi
-    echo "${els[0]}"
 }
 
 test_radio_list()
 {
-    local -a fav_colors=( black red green yellow blue magenta cyan white )
-    local -a fav_color_list
-    lui_list_convert "fav_color_list" "fav_colors" 1 2
+    local -a rawlist=( black red green brown blue magenta cyan white )
+    local -a clist
 
-    test_dump_list "fav_color_list"
+    lui_list_convert "clist" "rawlist" 1 2
 
-    local -a term_keys=(
-        "${LUI_DEFAULT_TERM_KEYS[@]}"
-        "j| :test_radio_toggler"
-    )
+    if lui_list_radio "clist"; then
+        report_selection "clist"
+    else
+        echo "Terminate radio without selection"
+    fi
 
-    local -i selection=0
-    lui_list_generic "selection" "fav_color_list" "test_radio_displayer" "8" "term_keys"
+    read -n1 -p "Press any key to continue."
+}
 
-    test_dump_list "fav_color_list"
+test_checkbox_list()
+{
+    local -a rawlist=( black red green brown blue magenta cyan white )
+    local -a clist
 
+    lui_list_convert "clist" "rawlist" 1 2
+
+    if lui_list_checkbox "clist"; then
+        report_selection "clist"
+    else
+        echo "Terminate checkbox without selection"
+    fi
+
+    read -n1 -p "Press any key to continue."
 }
 
 
-test_generic_custom()
+# Called by test_edit_ls_colors()
+test_generic_edit_color()
+{
+    local keyp="$1"
+    local list_name="$2"
+    local -i row_number="$3"
+
+    local -a row
+    if lui_list_copy_row "row" "$list_name" "$row_number"; then
+        local lcolor="${row[1]}"
+        if edit_color "lcolor"; then
+            row[1]="$lcolor"
+            lui_list_replace_row "$list_name" "row" "$row_number"
+        fi
+    else
+        echo "Error with lui_list_copy_row." >&2
+        read -n1
+    fi
+    return 0
+}
+
+test_edit_ls_colors()
 {
     local -a list_colors
     create_ls_colors_array "list_colors" 3
@@ -288,10 +304,46 @@ test_generic_custom()
     fi
 }
 
-# test_padding;     read -n1 -p "Any key to continue"
-# test_simple_menu; read -n1 -p "Any key to continue"
+##############
+#    Main    #
+##############
 
-# test_generic_menu
-# test_generic_custom
+declare -a MAIN_MENU=(
+    2 0
+    "test padding"          test_padding
+    "test ls_colors"        test_ls_colors
+    "test generic menu"     test_generic_menu
+    "test simple menu"      test_simple_menu
+    "test edit ls_colors"   test_edit_ls_colors
 
-test_radio_list
+    "test custom menu"      test_custom_menu
+    "test radio list"       test_radio_list
+    "test checkbox list"    test_checkbox_list
+    )
+
+lui_list_init "MAIN_MENU"
+
+main_menu()
+{
+    run_test()
+    {
+        local -a row=()
+        lui_list_copy_row "row" "$2" "$3"
+
+        # Execute the command
+        "${row[1]}"
+
+        return 0
+    }
+
+    local -a keylist=(
+        $'\e|q:LUI_ABORT'
+        $'\n:run_test'
+    )
+
+    local -i selected=0
+    lui_list_generic "selected" "MAIN_MENU" "" 10 "keylist"
+}
+
+main_menu
+
